### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/AcademicContent#255]
Create issue templates for this repo.

These should include templates for:

* New content wanted
* New content suggested for submission
* Broken links
* Inappropriate content
* Out of date content in need of an update
* Bugs - mistakes in the site
* Feature requests - new features wanted for this repo

**Comment by TaraJmitchell** [comment]
ok

**Comment by niyoj** [comment]
Is this issue still open to work on? @jimbobbennett

**Comment by jlooper** [comment]
@niyoj sure!

**Comment by niyoj** [comment]
@jlooper Working on that

**Comment by niyoj** [comment]
I have created PR for Bug report issue template
