### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rajvijay68** [microsoft/AcademicContent#259]
In the Azure portal, in the learning path,

The link to learning about Video indexer is broken  

https://github.com/microsoft/AcademicContent/blob/master/Labs/AI%20and%20Machine%20Learning/Video%20Indexer/Video%20Indexer.md

**EDIT** : It seems all the links are broken!

**Comment by jimbobbennett** [comment]
These labs have been removed as a lot of them were out of date or broken.

Where abouts in the Azure portal is the link? I can't find one anywhere.

**Comment by jimbobbennett** [comment]
The broken links are on these two sites:

https://ms.portal.azure.com/#blade/Microsoft_Azure_Education/EducationMenuBlade/learning
https://azure.microsoft.com/en-us/education/

**Comment by jimbobbennett** [comment]
Fixed by #261
