### ISSUE TITLE
Broken Link in docs/content/learning-content.md

### ISSUE THREAD

**Issue by ShreyaDhir** [microsoft/AcademicContent#300]
The link to the Learning Content - "Learning Python from Scratch" is broken. The video is currently private.

https://www.youtube.com/watch?v=q6bZcsOhwKk&list=PLG8WGLcszzgWec9s06fMn760bZ7LGV3ya

**Comment by jimbobbennett** [comment]
Good spot - that video series was removed, so I've removed it.
