### ISSUE TITLE
Broken link https://github.com/microsoft/computerscience/blob/master/Labs/Costs.md

### ISSUE THREAD

**Issue by tnfssc** [microsoft/AcademicContent#301]
_https://github.com/microsoft/computerscience/blob/master/Labs/Costs.md_ from _https://portal.azure.com/#blade/Microsoft_Azure_Education/EducationMenuBlade/templates, **Provision a function app running on an App Service Plan**_

**Comment by mertbozkir** [comment]
You are trying to open  Costs.md file, but this file isn't merge to master branch. Other branches have this file you can open in Azure-Developer-Day branch. Try this [link](https://github.com/microsoft/AcademicContent/tree/Azure-Developer-Day/Labs)
`Try this`
```diff 
- Master
+ Azure-Developer-Day 
```
