### ISSUE TITLE
Change default branch to "main"

### ISSUE THREAD

**Issue by FloorD** [microsoft/AcademicContent#303]
Could you consider changing the name of the default branch to "main"? For guidance: https://github.com/github/renaming/

**Comment by shanamatthews** [comment]
@jimbobbennett - we should 1000% change the name of the default branch!

**Comment by jimbobbennett** [comment]
Yes. Totally.

Done:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/1710385/107458803-aa3e0100-6b09-11eb-8c13-66bf7a828e4f.png">

The update should roll through in the next few minutes.
